roles/ocm-install-core/README.md
roles/ocm-install-core/tasks/main.yml
roles/ocm-install-core/tests/inventory
roles/ocm-install-core/tests/test.yml

- Added CRD wait to /resolve #11 
- Refactored tasks to fit inventory centric model

Refactor role ocm-install-core

---

.gitignore
plugins/module_utils/import_utils.py
plugins/modules/import_eks.py
requirements.txt
tests/integration/targets/import_eks/README.md
tests/integration/targets/import_eks/tasks/inventory
tests/integration/targets/import_eks/tasks/main.yml

Co-authored-by: Tara Gu <tgu@redhat.com>
Co-authored-by: Hao Liu <haoli@redhat.com>
Co-authored-by: Crystal Chun <cchun@redhat.com>
Co-authored-by: Hanqiu Zhang <hanzhang@redhat.com>
/cc @TheRealHaoLiu @CrystalChun @hanqiuzh

Add ocm-eks role and enable EKS cluster import

---

plugins/modules/import_eks.py

closes https://github.com/open-cluster-management/ocmplus.cm/issues/26

update addons in module argument spec

---

plugins/modules/import_eks.py

call aws module util to get aws account info

---

plugins/inventory/ocm_managedcluster.py
plugins/modules/cluster_proxy_addon.py
plugins/modules/import_eks.py
plugins/modules/managed_serviceaccount_addon.py

Issue: https://github.com/stolostron/backlog/issues/18784

fix author format to use only github

---

requirements.txt

Signed-off-by: Tsu Phin Hee <thee@redhat.com>

fix dependency

---

plugins/module_utils/import_utils.py
plugins/modules/import_eks.py
tests/integration/targets/import_eks/tasks/inventory
tests/integration/targets/import_eks/tasks/main.yml

Signed-off-by: Tsu Phin Hee <thee@redhat.com>

remove polling and backoff

---

plugins/module_utils/import_utils.py

fixes: https://github.com/stolostron/ocmplus.cm/issues/53

fix labels of managedclusters

---

plugins/modules/cluster_proxy_addon.py
plugins/modules/managed_serviceaccount_addon.py
requirements.txt

Signed-off-by: Tsu Phin Hee <thee@redhat.com>

add wait for proxy url available

---

plugins/modules/managed_serviceaccount.py

Updates:
- added field `ttl_seconds_after_creation` for managed-serviceaccount

add ttl for managed serviceaccount

---

plugins/module_utils/managedcluster_addons/addon_base.py
plugins/module_utils/managedcluster_addons/managed_serviceaccount.py

Updates:
- added MCE support for managed-serviceaccount addon

adding mce support

---

plugins/modules/managed_serviceaccount.py
tests/integration/targets/multicluster_management/tasks/multicluster-management-playbook.yml

fixes: https://github.com/stolostron/ocmplus.cm/issues/86

move the token & name to top level

---

plugins/modules/managed_serviceaccount.py
plugins/modules/managed_serviceaccount_rbac.py
tests/integration/targets/multicluster_management/tasks/multicluster-management-playbook.yml
tests/integration/targets/multicluster_management/tasks/rbac/role.yaml

closes https://github.com/stolostron/ocmplus.cm/issues/87

add option to configure name or generate_name for managed-serviceaccount

---

plugins/modules/managed_serviceaccount_rbac.py

- update description of rbac_template (and in the process realized there's a bug)
- when managed_serviceaccount_rbac is rerun due to the random generated string the manifestwork will be updated every time unnecessarily
- fix is to use the last 12 digit of the managed-serviceaccount resource as postfix
closes https://github.com/stolostron/ocmplus.cm/issues/88
Signed-off-by: Hao Liu <haoli@redhat.com>

update description of rbac_template arg also fix idempotentcy bug

---

.github/workflows/ansible-test.yml
plugins/modules/managed_serviceaccount_rbac.py
tests/integration/targets/multicluster_management/tasks/rbac/rolebinding.yaml
tests/integration/targets/multicluster_management/tasks/rbac/unused_role.yaml
tests/sanity/ignore-2.10.txt
tests/sanity/ignore-2.11.txt
tests/sanity/ignore-2.12.txt
tests/unit/plugins/modules/fixtures/rbac_template/bad_rbac.yml
tests/unit/plugins/modules/fixtures/rbac_template/five_object_file.yml
tests/unit/plugins/modules/fixtures/rbac_template/lorem_ipsum.txt
tests/unit/plugins/modules/fixtures/rbac_template/non_rbac_resource.yml
tests/unit/plugins/modules/fixtures/rbac_template/single_object_file.yml
tests/unit/plugins/modules/test_managed_serviceaccount_rbac.py

- add validation and protection against malformed rbac resource files
- fix bug where if rolebinding is processed before role the rolebinding roleRef is not renamed
- added unit test structure and implement some unit test for new methods
- run unit test in PR github action
- TODO: add manifestwork status validation (this may need to be split to a different PR)
closes #93

refactor core logic of managed_serviceaccount_rbac and add unit test structure

---

.github/workflows/ansible-test.yml
.github/workflows/docs-pr.yml
README.md
docs-build/build-readme.py
tests/Makefile
tests/README.md

Related issue: https://github.com/stolostron/ocmplus.cm/issues/98
(want to merge and then try out the doc pr update to build readme)

Readme update

---

plugins/module_utils/managedcluster_addons/managed_serviceaccount.py

update to use preview name

---

.github/workflows/docs-pr.yml
.github/workflows/galaxy-publish.yml
galaxy.yml

adding publish step for collection

---

.github/workflows/galaxy-publish.yml

fixing namespace and collection name in galaxy pub action

---

README.md
docs/cluster_management_addon_module.rst
docs/cluster_proxy_module.rst
docs/index.rst
docs/managed_serviceaccount_module.rst
docs/managed_serviceaccount_rbac_module.rst
docs/managedcluster_addon_module.rst
docs/ocm_managedcluster_inventory.rst
galaxy.yml

bumping version to 0.0.1-beta and fixing links to gh repo

---

README.md

fixing readme alpha.1

---

README.md

adding reference to demo repo

---

plugins/modules/cluster_proxy.py

in ACM 2.6 cluster-proxy moved from MultiClusterHub to MultiClusterEngine
when attempting to get the cluster proxy user route we will now check both the MultiClusterHub namespace and the MultiClusterEngine namespace
Signed-off-by: Hao Liu <haoli@redhat.com>

fix cluster-proxy addon for ACM 2.6

---

changelogs/changelog.yaml
galaxy.yml

- bump collection version in galaxy.yml
- add changelog for 0.0.2
Signed-off-by: Hao Liu <haoli@redhat.com>

update version to prep for release
